import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";

const SITE_URL = "https://scorchprotocol.com";
const DESCRIPTION =
  "A data-driven protocol for metabolic recovery from ME/CFS and Long Covid using dry fasting, T3 therapy, and hGH. 97% improvement across 141 participants.";

export const metadata: Metadata = {
  title: {
    default: "The Scorch Protocol",
    template: "%s | Scorch Protocol",
  },
  description: DESCRIPTION,
  metadataBase: new URL(SITE_URL),
  openGraph: {
    title: "The Scorch Protocol",
    description: DESCRIPTION,
    url: SITE_URL,
    siteName: "The Scorch Protocol",
    // OG image is generated by src/app/opengraph-image.tsx (1200x630 branded card).
    type: "website",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "The Scorch Protocol",
    description: DESCRIPTION,
    // Twitter card image is generated by src/app/twitter-image.tsx.
  },
  robots: {
    index: true,
    follow: true,
  },
};

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebSite",
      "@id": `${SITE_URL}/#website`,
      url: SITE_URL,
      name: "The Scorch Protocol",
      description: DESCRIPTION,
      potentialAction: {
        "@type": "SearchAction",
        target: {
          "@type": "EntryPoint",
          urlTemplate: `${SITE_URL}/faq?q={search_term_string}`,
        },
        "query-input": "required name=search_term_string",
      },
    },
    {
      "@type": "Organization",
      "@id": `${SITE_URL}/#organization`,
      name: "The Scorch Protocol",
      url: SITE_URL,
      logo: {
        "@type": "ImageObject",
        url: `${SITE_URL}/assets/scorch-logo.png`,
      },
      founder: {
        "@type": "Person",
        "@id": `${SITE_URL}/about#yannick`,
        name: "Yannick Wolfe",
        url: `${SITE_URL}/about`,
      },
      sameAs: ["https://dryfastingclub.com"],
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        {/* RSS autodiscovery */}
        <link
          rel="alternate"
          type="application/rss+xml"
          title="The Scorch Protocol Blog"
          href="/api/rss"
        />
      </head>
      <body>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
